name: CI
run-name: "build .#otb-dev"

permissions:
  contents: read
  id-token: write

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux
    runs-on: >-
      ${{ (matrix.system == 'x86_64-linux' && 'ubuntu-latest')
      || (matrix.system == 'aarch64-linux' && 'ubuntu-24.04-arm') }}

    steps:
      - uses: actions/checkout@v4

      - name: prepare /nix
        run: sudo mkdir /mnt/nix && sudo mount -m -o bind /mnt/nix /nix

      - name: install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            fallback = true
            http-connections = 128
            max-substitution-jobs = 128

      - name: nix build
        run: nix build --keep-going -L --system ${{ matrix.system }} .#otb-dev