name: CI

permissions:
  contents: read
  id-token: write

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux
    runs-on: >-
      ${{ (matrix.system == 'x86_64-linux' && 'ubuntu-latest')
      || (matrix.system == 'aarch64-linux' && 'ubuntu-24.04-arm') }}

    steps:
      - uses: actions/checkout@v4

      - name: prepare /nix
        run: sudo mkdir /mnt/nix && sudo mount -m -o bind /mnt/nix /nix

      - name: install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            fallback = true
            http-connections = 128
            max-substitution-jobs = 128

      - name: Debug CPU info files
        run: |
          echo "=== Checking CPU info files ==="
          echo "Architecture: $(uname -m)"
          echo "Kernel: $(uname -r)"
          
          echo "--- /sys/devices/system/cpu/possible ---"
          if [ -f /sys/devices/system/cpu/possible ]; then
            echo "File exists"
            echo "Content: $(cat /sys/devices/system/cpu/possible 2>/dev/null || echo 'Cannot read')"
            echo "Permissions: $(ls -la /sys/devices/system/cpu/possible)"
          else
            echo "File does not exist"
          fi
          
          echo "--- /sys/devices/system/cpu/present ---"
          if [ -f /sys/devices/system/cpu/present ]; then
            echo "File exists"
            echo "Content: $(cat /sys/devices/system/cpu/present 2>/dev/null || echo 'Cannot read')"
            echo "Permissions: $(ls -la /sys/devices/system/cpu/present)"
          else
            echo "File does not exist"
          fi
          
          echo "--- /sys/devices/system/cpu/ directory ---"
          echo "Directory contents:"
          ls -la /sys/devices/system/cpu/ || echo "Directory does not exist"
          
          echo "--- CPU info from /proc/cpuinfo ---"
          echo "Number of processors: $(nproc)"
          echo "CPU info (first 10 lines):"
          head -10 /proc/cpuinfo || echo "Cannot read /proc/cpuinfo"
          
          echo "--- Available CPU directories ---"
          ls -la /sys/devices/system/cpu/cpu* 2>/dev/null | head -5 || echo "No CPU directories found"

      - name: nix build
        run: nix build --keep-going -L --system ${{ matrix.system }} .#otb-dev